server:
  port: 8884

spring:
  application:
    name: gassman-admin
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka