server:
  port: 8884

spring:
  application:
    name: gassman-admin
  rabbitmq:
    addresses: amqp://tmwtbfjj:fXhbTFsfVvw_hIwTshosVKn4IxFpV69X@stingray.rmq.cloudamqp.com/tmwtbfjj
  cloud:
    stream:
      bindings:
        userRegistrationChannel:
          destination: gassman-user-registration
        userOrderChannel:
          destination: gassman-order-registration
        orderPaymentConfirmationChannel:
          destination: gassman-order-payment-confirmation
        userCancellationChannel:
          destination: gassman-user-cancellation
  banner:
    location: gassman.txt

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8880/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000

label:
  button:
    userManagement: Users management
    userNew: New User
    productManagement: Products management
    productNew: New Product
    save: Save
    reset: Reset
    delete: Delete
    supplier: Click to copy to clipboard the supplier link

  user:
    firstname: First name
    lastname: Last name
    mail: Mail
    active: is Active
    credit: Credit for internal payment system (€)
    newCredit: New Credit
    oldCredit: Old Credit
    rechargeUserCreditType: Recharge Type
    rechargeDateTime: Recharge DateTime
    administrator: Administrator
    cashFund: Cash fund
  product:
    name: Name
    description: Description
    unitOfMeasure: Unit of Measure
    pricePerUnit: Price per Unit
    availableQuantity: Available Quantity
    deliveryDateTime: Delivery date
    active: is Active
    bookedQuantity: Booked quantity
    showHistory: Show past products
    urlOrderPublic: http://localhost:8881/gassman-order-service/public/products/
  order:
    user: User
    quantity: Quantity
    totalToPay: Total To Pay
    paid: Paid
    paymentExternalReference: Payment External Reference
    paymentExternalDateTime: Payment External Date
    totalAmountSupplier: Total amount due to supplier

admin:
  username: admin
  password: $2a$10$q3N/aKgnRhogokVQO8BnduFAMbHfv6VzUKI0g3JQdAHhncz7OdTBC

gassman:
  api:
    username:
    password: